name: webrtc-pqc
services:
  - name: web
    dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
      repo: maciejkra/webrtc-pqc-poc
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    health_check:
      http_path: /api/info
      initial_delay_seconds: 10
      period_seconds: 30
